development:
  token: RtaS7BZ3xafKlG36cLNJQ
  secret: u3hvB3s1VDkZsCvnAglT2F3DMZPQ4NIkSWom1fxaFE

test:
  token: RtaS7BZ3xafKlG36cLNJQ
  secret: u3hvB3s1VDkZsCvnAglT2F3DMZPQ4NIkSWom1fxaFE

production:
  token: RtaS7BZ3xafKlG36cLNJQ
  secret: u3hvB3s1VDkZsCvnAglT2F3DMZPQ4NIkSWom1fxaFE
